# Generated by Django 6.0 on 2025-12-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_plugin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='readme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
