# Generated by Django 6.0 on 2025-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_plugin_readme'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
