# Generated by Django 6.0 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_plugin_submitted_by_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='diagram_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
