# Generated by Django 6.0 on 2025-12-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_plugin_diagram_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginEnvVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('accept', models.CharField(blank=True, max_length=255, null=True)),
                ('multiple', models.BooleanField(default=False)),
                ('sourceFile', models.CharField(blank=True, max_length=255, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('step', models.FloatField(blank=True, null=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_variables', to='plugins.plugin')),
            ],
        ),
    ]
