# Generated by Django 6.0 on 2025-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_pluginenvvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
