# Generated by Django 6.0 on 2025-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_add_update_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='environments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
