# Generated by Django 6.0 on 2025-12-27 22:10

import django.db.models.deletion
import plugins.encrypted_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0010_runtime_environments_alter_runtime_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositorySSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.CharField(max_length=500)),
                ('ssh_private_key', plugins.encrypted_fields.EncryptedTextField()),
                ('passphrase', plugins.encrypted_fields.EncryptedCharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'repository_url')},
            },
        ),
    ]
