# Generated by Django 6.0 on 2025-12-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_repositorysshkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='requires_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
