# Generated by Django 6.0 on 2025-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_plugin_requires_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='plugins', through='plugins.PluginTag', to='plugins.tag'),
        ),
    ]
