# Generated by Django 6.0 on 2026-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_add_schema_v2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='citation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
