# Generated by Django 6.0 on 2026-02-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0015_plugin_citation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="input",
            name="accept",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="disableAnnotationManagement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="input",
            name="groups",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="groupsFromFile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="optionsFromFile",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="tableColumns",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="input",
            name="visibleWhen",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runtime",
            name="docker",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "samplesFrom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "annotationFile",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="plugins.plugin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("values", models.JSONField(blank=True, null=True)),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example",
                        to="plugins.plugin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("argsMapping", models.JSONField(blank=True, null=True)),
                ("outputDir", models.CharField(blank=True, max_length=255, null=True)),
                ("requirements", models.JSONField(blank=True, null=True)),
                (
                    "plugin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="plugins.plugin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=50)),
                ("component", models.CharField(max_length=255)),
                ("dataSource", models.CharField(max_length=255)),
                ("config", models.JSONField(blank=True, null=True)),
                ("customization", models.JSONField(blank=True, null=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="plugins.plugin",
                    ),
                ),
            ],
        ),
    ]
