# Generated by Django 6.0 on 2026-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0016_add_schema_v2_complete_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugin",
            name="schema_version",
            field=models.IntegerField(default=0),
        ),
    ]
